# Gin 开发环境 Dockerfile
# 支持热重载

FROM golang:1.21-alpine

RUN apk add --no-cache git make && \
    go install github.com/cosmtrek/air@latest

ENV GO111MODULE=on \
    GOPROXY=https://goproxy.cn,direct

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
